In [1]:
! pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.63.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2021.10.8)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)

In [2]:
! mkdir ~/.kaggle

In [3]:
! cp kaggle.json ~/.kaggle/

In [4]:
! chmod 600 ~/.kaggle/kaggle.json

In [5]:
! kaggle competitions download -c nitro-lang-processing-1

Downloading nitro-lang-processing-1.zip to /content
  0% 0.00/2.87M [00:00<?, ?B/s]
100% 2.87M/2.87M [00:00<00:00, 52.1MB/s]

In [6]:
! unzip nitro-lang-processing-1.zip

Archive:  nitro-lang-processing-1.zip
  inflating: random_seed_setter.py
  inflating: sample_submission.csv
  inflating: tag_to_id.json
  inflating: teams_rand_seed.csv
  inflating: test.json
  inflating: train.json

In [115]:
import json
import pandas as pd

In [116]:
path = './train.json'

In [117]:
continuturi = pd.read_json(path)

In [118]:
continuturi

,ner_tags,ner_ids,tokens,space_after
0,"[O, GPE, O, O, O, O, O, O, LOC, O, O, O, O, O,...","[0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, ...","[În, România, ,, ca, de, altfel, în, întreaga,...","[True, False, True, True, True, True, True, Tr..."
1,"[O, O, O, DATETIME, DATETIME, O, O, O, O, O, O...","[0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 13, 13, 1...","[Se, estimează, că, în, prezent, acestea, sunt...","[True, True, True, True, True, True, True, Tru..."
2,"[O, O, O, O, O, NUMERIC, O, O, O, PERSON, O, P...","[0, 0, 0, 0, 0, 13, 0, 0, 0, 1, 0, 1, 0, 0, 1,...","[Cartea, cuprinde, o, suită, de, 115, texte-re...","[True, True, True, True, True, True, True, Tru..."
3,"[O, O, O, O, O, O, O, O, O, O, O, DATETIME, DA...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 9, 9, 0]","[Bursele, pentru, proiecte, ArtsLink, -, terme...","[True, True, True, True, True, True, True, Tru..."
4,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Aplicația, informațională, este, însoțită, de...","[True, True, True, True, True, True, True, Tru..."
...,...,...,...,...
12325,"[O, O, NUMERIC, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[În, Capitolul, IV, “, Rolul, unităților, de, ...","[True, True, True, False, True, True, True, Tr..."
12326,"[O, O, O, O, O, GPE, O, O, O, O, GPE, O, GPE, ...","[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 3, 0, 0, ...","[Naționala, de, volei, masculin, a, României, ...","[True, True, True, True, True, True, True, Fal..."
12327,"[PERSON, O, O, O, O, ORG, O, PERSON, PERSON, O...","[1, 0, 0, 0, 0, 2, 0, 1, 1, 0, 2, 0, 0, 0, 0, ...","[Președintele, Comisiei, de, Buget, a, Senatul...","[True, True, True, True, True, False, True, Tr..."
12328,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Majorarea, este, justificată, de, benzinari, ...","[True, True, True, True, True, True, True, Tru..."
12329,"[O, O, O, PERSON, O, O, O, O, O, O, O, O, O, O...","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Între, timp, ,, concubina, acestuia, și-, a, ...","[True, False, True, True, True, False, True, T..."

In [119]:
import collections
all_words = []

for x in continuturi['ner_tags']:
  for entry in x:
    all_words.append(entry)

counter = collections.Counter(all_words)
frequency_df = pd.DataFrame(counter.most_common(len(counter)), columns=["word", "frequency"])
frequency_df

           word  frequency
0             O     412266
1        PERSON      39283
2      DATETIME      21442
3           ORG      20370
4           GPE      12808
5       NUMERIC       8031
6   WORK_OF_ART       7119
7           LOC       5533
8   NAT_REL_POL       5061
9         MONEY       4098
10       PERIOD       3678
11        EVENT       3625
12     FACILITY       3401
13      ORDINAL       3084
14     QUANTITY       2694
15     LANGUAGE        670

In [120]:
id_to_tag = {0: "O", 1: "PERSON", 12: "QUANTITY", 13: "NUMERIC", 5: "NAT_REL_POL", 3: "GPE",  9:"DATETIME", 2: "ORG", 10: "PERIOD", 6: "EVENT", 15: "FACILITY", 14: "ORDINAL", 4:"LOC", 11:"MONEY", 8: "WORK_OF_ART", 7: "LANGUAGE"}

In [121]:
import collections
all_words = []

#for x in continuturi['ner_tags']:
for entry in all_token_pred:
  all_words.append(id_to_tag[entry])

counter = collections.Counter(all_words)
frequency_df = pd.DataFrame(counter.most_common(len(counter)), columns=["word", "frequency"])
frequency_df

           word  frequency
0             O      56031
1        PERSON       4439
2           GPE       3013
3      DATETIME       2573
4           ORG       1670
5   WORK_OF_ART       1046
6       NUMERIC        741
7   NAT_REL_POL        588
8           LOC        575
9      LANGUAGE        523
10     QUANTITY        478
11       PERIOD        441
12     FACILITY        384
13        EVENT        330
14      ORDINAL        270
15        MONEY        174

In [122]:
def varianta_1(text):
  # sterg stop words, stemming, elimin punctuatua, normalizam cu tf-idf
  text = [x.lower() for x in text]                          
  return text

In [80]:
#continuturi['tokens'] = continuturi.tokens.apply(varianta_1)

In [81]:
continuturi.describe()

,ner_tags,ner_ids,tokens,space_after,sentences
count,12330,12330,12330,12330,12330
unique,12064,12064,12326,10823,12326
top,"[O, O, O, O, O, NUMERIC, O, PERSON, O, O, O, G...","[0, 0, 0, 0, 0, 13, 0, 1, 0, 0, 0, 3, 0, 0, 0,...","[conducătorul, auto, leonard, nicol, s., ,, de...","[True, True, True, True, True, True, True, Tru...","CONDUCĂTORUL AUTO LEONARD NICOL S., DE 31 DE A..."
freq,21,21,2,42,2

In [123]:
continuturi

,ner_tags,ner_ids,tokens,space_after
0,"[O, GPE, O, O, O, O, O, O, LOC, O, O, O, O, O,...","[0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, ...","[În, România, ,, ca, de, altfel, în, întreaga,...","[True, False, True, True, True, True, True, Tr..."
1,"[O, O, O, DATETIME, DATETIME, O, O, O, O, O, O...","[0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 13, 13, 1...","[Se, estimează, că, în, prezent, acestea, sunt...","[True, True, True, True, True, True, True, Tru..."
2,"[O, O, O, O, O, NUMERIC, O, O, O, PERSON, O, P...","[0, 0, 0, 0, 0, 13, 0, 0, 0, 1, 0, 1, 0, 0, 1,...","[Cartea, cuprinde, o, suită, de, 115, texte-re...","[True, True, True, True, True, True, True, Tru..."
3,"[O, O, O, O, O, O, O, O, O, O, O, DATETIME, DA...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 9, 9, 0]","[Bursele, pentru, proiecte, ArtsLink, -, terme...","[True, True, True, True, True, True, True, Tru..."
4,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Aplicația, informațională, este, însoțită, de...","[True, True, True, True, True, True, True, Tru..."
...,...,...,...,...
12325,"[O, O, NUMERIC, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...","[În, Capitolul, IV, “, Rolul, unităților, de, ...","[True, True, True, False, True, True, True, Tr..."
12326,"[O, O, O, O, O, GPE, O, O, O, O, GPE, O, GPE, ...","[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 3, 0, 3, 0, 0, ...","[Naționala, de, volei, masculin, a, României, ...","[True, True, True, True, True, True, True, Fal..."
12327,"[PERSON, O, O, O, O, ORG, O, PERSON, PERSON, O...","[1, 0, 0, 0, 0, 2, 0, 1, 1, 0, 2, 0, 0, 0, 0, ...","[Președintele, Comisiei, de, Buget, a, Senatul...","[True, True, True, True, True, False, True, Tr..."
12328,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Majorarea, este, justificată, de, benzinari, ...","[True, True, True, True, True, True, True, Tru..."
12329,"[O, O, O, PERSON, O, O, O, O, O, O, O, O, O, O...","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Între, timp, ,, concubina, acestuia, și-, a, ...","[True, False, True, True, True, False, True, T..."

In [124]:
n = len(continuturi)
sentences = []
for i in range(n):
    sentence = ""
    for j, token in enumerate(continuturi["tokens"][i]):
        sentence += token
        if continuturi["space_after"][i][j]:
            sentence += " "
    sentences.append(sentence)

continuturi["sentences"] = sentences

continuturi.head()

,ner_tags,ner_ids,tokens,space_after,sentences
0,"[O, GPE, O, O, O, O, O, O, LOC, O, O, O, O, O,...","[0, 3, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, ...","[În, România, ,, ca, de, altfel, în, întreaga,...","[True, False, True, True, True, True, True, Tr...","În România, ca de altfel în întreaga Europă, s..."
1,"[O, O, O, DATETIME, DATETIME, O, O, O, O, O, O...","[0, 0, 0, 9, 9, 0, 0, 0, 0, 0, 0, 0, 13, 13, 1...","[Se, estimează, că, în, prezent, acestea, sunt...","[True, True, True, True, True, True, True, Tru...",Se estimează că în prezent acestea sunt utiliz...
2,"[O, O, O, O, O, NUMERIC, O, O, O, PERSON, O, P...","[0, 0, 0, 0, 0, 13, 0, 0, 0, 1, 0, 1, 0, 0, 1,...","[Cartea, cuprinde, o, suită, de, 115, texte-re...","[True, True, True, True, True, True, True, Tru...",Cartea cuprinde o suită de 115 texte-remember ...
3,"[O, O, O, O, O, O, O, O, O, O, O, DATETIME, DA...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 9, 9, 0]","[Bursele, pentru, proiecte, ArtsLink, -, terme...","[True, True, True, True, True, True, True, Tru...",Bursele pentru proiecte ArtsLink - termen limi...
4,"[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[Aplicația, informațională, este, însoțită, de...","[True, True, True, True, True, True, True, Tru...",Aplicația informațională este însoțită de un s...

In [125]:
continuturi['sentences'][0]

'În România, ca de altfel în întreaga Europă, stand up-ul este forma de divertisment cea mai îndrăgită de tineri în acest moment, comediantii reușind să umple săli care erau destinate mai degrabă artiștilor din zona muzicii pop rock, iar Badea, Bordea și Micutzu sunt printre cei care au contribuit direct la succesul acestei forme de divertisment în țara noastră.'

In [126]:
continuturi['sentences'][1]

'Se estimează că în prezent acestea sunt utilizate de mai mult de 50 de milioane de persoane fizice și juridice din lumea întreagă.'

In [88]:
! pip install simpletransformers

Requirement already satisfied: simpletransformers in /usr/local/lib/python3.7/dist-packages (0.63.6)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (2.8.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (1.0.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (2.0.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (0.1.96)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (1.4.1)
Requirement already satisfied: seqeval in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (1.2.2)
Requirement already satisfied: regex in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (2019.12.20)
Requirement already satisfied: transformers>=4.6.0 in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (4.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (1.21.5)
Requirement already satisfied: streamlit in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (1.8.0)
Requirement already satisfied: tokenizers in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (0.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (2.23.0)
Requirement already satisfied: wandb>=0.10.32 in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (0.12.11)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (1.3.5)
Requirement already satisfied: tqdm>=4.47.0 in /usr/local/lib/python3.7/dist-packages (from simpletransformers) (4.63.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers>=4.6.0->simpletransformers) (3.6.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /usr/local/lib/python3.7/dist-packages (from transformers>=4.6.0->simpletransformers) (0.4.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from transformers>=4.6.0->simpletransformers) (21.3)
Requirement already satisfied: sacremoses in /usr/local/lib/python3.7/dist-packages (from transformers>=4.6.0->simpletransformers) (0.0.49)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers>=4.6.0->simpletransformers) (4.11.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.7/dist-packages (from transformers>=4.6.0->simpletransformers) (6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from huggingface-hub<1.0,>=0.1.0->transformers>=4.6.0->simpletransformers) (3.10.0.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->transformers>=4.6.0->simpletransformers) (3.0.7)
Requirement already satisfied: protobuf>=3.12.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (3.17.3)
Requirement already satisfied: sentry-sdk>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (1.5.8)
Requirement already satisfied: yaspin>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (2.1.0)
Requirement already satisfied: python-dateutil>=2.6.1 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (2.8.2)
Requirement already satisfied: promise<3,>=2.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (2.3)
Requirement already satisfied: pathtools in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (0.1.2)
Requirement already satisfied: docker-pycreds>=0.4.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (0.4.0)
Requirement already satisfied: GitPython>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (3.1.27)
Requirement already satisfied: psutil>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (5.4.8)
Requirement already satisfied: setproctitle in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (1.2.2)
Requirement already satisfied: shortuuid>=0.5.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (1.0.8)
Requirement already satisfied: Click!=8.0.0,>=7.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (7.1.2)
Requirement already satisfied: six>=1.13.0 in /usr/local/lib/python3.7/dist-packages (from wandb>=0.10.32->simpletransformers) (1.15.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.7/dist-packages (from GitPython>=1.0.0->wandb>=0.10.32->simpletransformers) (4.0.9)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.7/dist-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb>=0.10.32->simpletransformers) (5.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->simpletransformers) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->simpletransformers) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->simpletransformers) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->simpletransformers) (1.25.11)
Requirement already satisfied: termcolor<2.0.0,>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from yaspin>=1.0.0->wandb>=0.10.32->simpletransformers) (1.1.0)
Requirement already satisfied: dill in /usr/local/lib/python3.7/dist-packages (from datasets->simpletransformers) (0.3.4)
Requirement already satisfied: pyarrow>=5.0.0 in /usr/local/lib/python3.7/dist-packages (from datasets->simpletransformers) (6.0.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.7/dist-packages (from datasets->simpletransformers) (0.70.12.2)
Requirement already satisfied: responses<0.19 in /usr/local/lib/python3.7/dist-packages (from datasets->simpletransformers) (0.18.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.7/dist-packages (from datasets->simpletransformers) (3.8.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.7/dist-packages (from datasets->simpletransformers) (3.0.0)
Requirement already satisfied: fsspec[http]>=2021.05.0 in /usr/local/lib/python3.7/dist-packages (from datasets->simpletransformers) (2022.2.0)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets->simpletransformers) (1.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets->simpletransformers) (6.0.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets->simpletransformers) (21.4.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets->simpletransformers) (2.0.12)
Requirement already satisfied: asynctest==0.13.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets->simpletransformers) (0.13.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets->simpletransformers) (1.7.2)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets->simpletransformers) (1.3.0)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.7/dist-packages (from aiohttp->datasets->simpletransformers) (4.0.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers>=4.6.0->simpletransformers) (3.7.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->simpletransformers) (2018.9)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers>=4.6.0->simpletransformers) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn->simpletransformers) (3.1.0)
Requirement already satisfied: toml in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (0.10.2)
Requirement already satisfied: pydeck>=0.1.dev5 in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (0.7.1)
Requirement already satisfied: tornado>=5.0 in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (5.1.1)
Requirement already satisfied: validators in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (0.18.2)
Requirement already satisfied: altair>=3.2.0 in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (4.2.0)
Requirement already satisfied: semver in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (2.13.0)
Requirement already satisfied: cachetools>=4.0 in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (4.2.4)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (1.5.1)
Requirement already satisfied: watchdog in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (2.1.7)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (7.1.2)
Requirement already satisfied: blinker in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (1.4)
Requirement already satisfied: pympler>=0.9 in /usr/local/lib/python3.7/dist-packages (from streamlit->simpletransformers) (1.0.1)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit->simpletransformers) (4.3.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit->simpletransformers) (0.4)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit->simpletransformers) (2.11.3)
Requirement already satisfied: toolz in /usr/local/lib/python3.7/dist-packages (from altair>=3.2.0->streamlit->simpletransformers) (0.11.2)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit->simpletransformers) (0.18.1)
Requirement already satisfied: importlib-resources>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from jsonschema>=3.0->altair>=3.2.0->streamlit->simpletransformers) (5.4.0)
Requirement already satisfied: ipykernel>=5.1.2 in /usr/local/lib/python3.7/dist-packages (from pydeck>=0.1.dev5->streamlit->simpletransformers) (6.9.2)
Requirement already satisfied: ipywidgets>=7.0.0 in /usr/local/lib/python3.7/dist-packages (from pydeck>=0.1.dev5->streamlit->simpletransformers) (7.7.0)
Requirement already satisfied: traitlets>=4.3.2 in /usr/local/lib/python3.7/dist-packages (from pydeck>=0.1.dev5->streamlit->simpletransformers) (5.1.1)
Requirement already satisfied: matplotlib-inline<0.2.0,>=0.1.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.1.3)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (1.5.4)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (7.32.0)
Requirement already satisfied: debugpy<2.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (1.0.0)
Requirement already satisfied: jupyter-client<8.0 in /usr/local/lib/python3.7/dist-packages (from ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (5.3.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.2.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (2.6.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (3.0.28)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (4.4.2)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.18.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.7.5)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (57.4.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.7/dist-packages (from ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (4.8.0)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.2.0)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (1.1.0)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (5.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.7/dist-packages (from ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (3.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.8.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from jinja2->altair>=3.2.0->streamlit->simpletransformers) (2.0.1)
Requirement already satisfied: jupyter-core>=4.6.0 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (4.9.2)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python3.7/dist-packages (from jupyter-client<8.0->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (22.3.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipykernel>=5.1.2->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.2.5)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.7/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (5.3.1)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (5.6.1)
Requirement already satisfied: Send2Trash in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (1.8.0)
Requirement already satisfied: terminado>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.13.3)
Requirement already satisfied: mistune<2,>=0.8.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.8.4)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.6.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (1.5.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.7.1)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/dist-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (4.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/dist-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.0.0->pydeck>=0.1.dev5->streamlit->simpletransformers) (0.5.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (3.3.6)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (0.4.6)
Requirement already satisfied: grpcio>=1.24.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (1.44.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (1.8.1)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (1.0.1)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (1.0.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (1.35.0)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.7/dist-packages (from tensorboard->simpletransformers) (0.37.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->simpletransformers) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->simpletransformers) (4.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->simpletransformers) (1.3.1)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->simpletransformers) (0.4.8)

In [127]:
sentences_id = []
words = []
tags = []

for i in range(n):
  for j, token in enumerate(continuturi["tokens"][i]):
    sentences_id.append(i)
    words.append(token)
    tags.append(continuturi["ner_tags"][i][j])

print(sentences_id[:10])
print(words[:10])
print(tags[:10])

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
['În', 'România', ',', 'ca', 'de', 'altfel', 'în', 'întreaga', 'Europă', ',']
['O', 'GPE', 'O', 'O', 'O', 'O', 'O', 'O', 'LOC', 'O']

In [128]:
train_data = pd.DataFrame({"sentence_id":sentences_id, "words": words, "labels":tags})

train_data

        sentence_id    words labels
0                 0       În      O
1                 0  România    GPE
2                 0        ,      O
3                 0       ca      O
4                 0       de      O
...             ...      ...    ...
553158        12329        a      O
553159        12329    ieșit      O
553160        12329       în      O
553161        12329   stradă      O
553162        12329        .      O

[553163 rows x 3 columns]

In [129]:
from simpletransformers.ner import NERModel, NERArgs

In [155]:
labels = train_data['labels'].unique().tolist()
labels

['O',
 'GPE',
 'LOC',
 'PERSON',
 'DATETIME',
 'NUMERIC',
 'ORG',
 'EVENT',
 'NAT_REL_POL',
 'QUANTITY',
 'ORDINAL',
 'PERIOD',
 'FACILITY',
 'WORK_OF_ART',
 'MONEY',
 'LANGUAGE']

In [191]:
args = NERArgs()
args.num_train_epochs = 3
args.learning_rate = 1e-4
args.overwrite_output_dir = True
args.train_batch_size = 32
args.eval_batch_size = 32

In [193]:
model = NERModel('bert', 'bert-base-cased', labels=labels, args=args)

RuntimeError: ignored

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
model.train_model(train_data, acc=accuracy_score)

In [ ]:
import pickle
pickle.dump(model, open('model.pkl', 'wb'))

In [ ]:
prediction, model_output = model.predict(['În România, ca de altfel în întreaga Europă, stand up-ul este forma de divertisment cea mai îndrăgită de tineri în acest moment, comediantii reușind să umple săli care erau destinate mai degrabă artiștilor din zona muzicii pop rock, iar Badea, Bordea și Micutzu sunt printre cei care au contribuit direct la succesul acestei forme de divertisment în țara noastră.', 'Se estimează că în prezent acestea sunt utilizate de mai mult de 50 de milioane de persoane fizice și juridice din lumea întreagă.'])

In [ ]:
prediction

In [ ]:
test_path = './test.json'
test_content = pd.read_json(test_path)

In [163]:
test_content

,tokens,space_after,sentences
0,"[Cazul, tinerei, agresate, de, agenții, de, pa...","[True, True, True, True, True, True, True, Fal...",Cazul tinerei agresate de agenții de pază într...
1,"[\n, Scandal, la, Carrefour, Braşov, :, Unde, ...","[False, True, True, True, False, True, True, T...",endl Scandal la Carrefour Braşov : Unde se poa...
2,"[De, ce, câștigă, Facebook, și, când, utilizat...","[True, True, True, True, True, True, True, Tru...",De ce câștigă Facebook și când utilizatorii îș...
3,"[EXCLUSIV, !, Tupeu, fără, margini, !, Profi, ...","[False, True, True, True, False, True, True, T...",EXCLUSIV ! Tupeu fără margini ! Profi șochează...
4,"[PROFI, ,, în, mijlocul, unui, scandal, !, Rep...","[False, True, True, True, True, False, True, T...","PROFI , în mijlocul unui scandal ! Reprezentan..."
...,...,...,...
2416,"[34,18, dolari, SUA, ,, voi, cumpăra, 5, mii, ...","[True, True, False, True, True, True, True, Tr...","34,18 dolari SUA , voi cumpăra 5 mii de acțiun..."
2417,"[$, RH, Interes, scurt, imens, ., Toate, vânză...","[True, True, True, True, False, True, True, Tr...",$ RH Interes scurt imens . Toate vânzările cu ...
2418,"[$, TVIX, în, @, 10,07, $, vă, rugăm, să, nu, ...","[True, True, True, True, True, True, True, Tru...","$ TVIX în @ 10,07 $ vă rugăm să nu mai vindeți..."
2419,"[$, AAPL, piatră, de, mormânt, care, indică, o...","[True, True, True, True, True, True, True, Tru...",$ AAPL piatră de mormânt care indică o presiun...
2420,"[$, WY, supraevaluat, ...., îmi, pare, rău, ,,...","[True, True, True, True, True, True, False, Tr...","$ WY supraevaluat .... îmi pare rău , oameni b..."

In [ ]:
#test_content['tokens'] = test_content.tokens.apply(varianta_1)

In [164]:
n_test = len(test_content)
sentences = []
for i in range(n_test):
    sentence = ""
    for j, token in enumerate(test_content["tokens"][i]):
        if token == '\n' or token == '\n ':
          sentence += 'endl'
        elif token == ' ':
          sentence += 'space'
        else:
          sentence += token
        sentence += " "
    sentences.append(sentence[:-1])

test_content["sentences"] = sentences

test_content.head()

,tokens,space_after,sentences
0,"[Cazul, tinerei, agresate, de, agenții, de, pa...","[True, True, True, True, True, True, True, Fal...",Cazul tinerei agresate de agenții de pază într...
1,"[\n, Scandal, la, Carrefour, Braşov, :, Unde, ...","[False, True, True, True, False, True, True, T...",endl Scandal la Carrefour Braşov : Unde se poa...
2,"[De, ce, câștigă, Facebook, și, când, utilizat...","[True, True, True, True, True, True, True, Tru...",De ce câștigă Facebook și când utilizatorii îș...
3,"[EXCLUSIV, !, Tupeu, fără, margini, !, Profi, ...","[False, True, True, True, False, True, True, T...",EXCLUSIV ! Tupeu fără margini ! Profi șochează...
4,"[PROFI, ,, în, mijlocul, unui, scandal, !, Rep...","[False, True, True, True, True, False, True, T...","PROFI , în mijlocul unui scandal ! Reprezentan..."

In [165]:
tag_to_id = json.load(open('tag_to_id.json'))

In [166]:
tag_to_id

{'O': 0,
 'PERSON': 1,
 'QUANTITY': 12,
 'NUMERIC': 13,
 'NAT_REL_POL': 5,
 'GPE': 3,
 'DATETIME': 9,
 'ORG': 2,
 'PERIOD': 10,
 'EVENT': 6,
 'FACILITY': 15,
 'ORDINAL': 14,
 'LOC': 4,
 'MONEY': 11,
 'WORK_OF_ART': 8,
 'LANGUAGE': 7}

In [167]:
predictions, model_output = model.predict([test_content['sentences'][0]])

AttributeError: ignored

In [ ]:
print(tag_to_id[list(predictions[0][0].values())[0]])
print(len(predictions[0]))

In [ ]:
all_predictions = []

predictions, model_output = model.predict(list(test_content['sentences']))

In [ ]:
print(len(predictions))

In [ ]:
gresite = 0
for i, prediction in enumerate(predictions):
  if len(prediction) != len(test_content['tokens'][i]):
    print(i, len(prediction), len(test_content['tokens'][i]))

print(gresite)

In [ ]:
print(test_content['sentences'][1438])
print(test_content['tokens'][1438])
print(predictions[1438])

In [ ]:
for i,prediction in enumerate(predictions):
  sentence_prediction = []
  if len(prediction) == len(test_content['tokens'][i]):
    for j in range(len(prediction)):
      sentence_prediction.append(tag_to_id[list(prediction[j].values())[0]])
  else:
    for token in test_content['tokens'][i]:
      for p in prediction:
        if token == list(p.keys())[0]:
          sentence_prediction.append(tag_to_id[list(p.values())[0]])
          break
      else:
        sentence_prediction.append(tag_to_id['O'])
  all_predictions.append(sentence_prediction)

In [ ]:
gresite = 0
for i in range(len(all_predictions)):
  if len(all_predictions[i]) != len(test_content['tokens'][i]):
    gresite += 1

print(gresite)

In [174]:
all_predictions[0][0]

{'entity': 'LABEL_0',
 'score': 0.9990716,
 'index': 1,
 'word': 'Cazul',
 'start': 0,
 'end': 5}

In [181]:
len(all_predictions)

2421

In [185]:
len(finals)

82930

In [179]:
all_token_pred = []
for sentence in all_predictions:
  for token_pred in sentence:
    all_token_pred.append(token_pred)

total = 0
for tokens in test_content['tokens']:
  total += len(tokens)

print(len(all_token_pred))
print(total)

91349
73276

In [ ]:
import csv

header = ['Id', 'ner_label']

with open('submission_bert_3.csv', 'w') as f:
  writer = csv.writer(f)
  writer.writerow(header)
  for i, pred_label in enumerate(all_token_pred):
    writer.writerow([i, pred_label])